/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package passagens;

/**
 *
 * @author deciodecarvalho
 */
public class TelaEscolhaAssento extends javax.swing.JFrame {

    /**
     * Creates new form TelaEscolhaAssento
     */
    public TelaEscolhaAssento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelRelTituloPassageiro = new javax.swing.JPanel();
        lblTituloMapaAssentos = new javax.swing.JLabel();
        lblIconeTelaMapaPassagens = new javax.swing.JLabel();
        tabMapaAssentos = new javax.swing.JTabbedPane();
        painelSelecaoMapaAssentos = new javax.swing.JPanel();
        btnMostraMapaAssentos = new javax.swing.JButton();
        lblOpcaoMostra = new javax.swing.JLabel();
        jScrollPanelMapaAssentos = new javax.swing.JScrollPane();
        painelBotoes = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PainelRelTituloPassageiro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        lblTituloMapaAssentos.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        lblTituloMapaAssentos.setForeground(new java.awt.Color(102, 102, 102));
        lblTituloMapaAssentos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloMapaAssentos.setText("Aerofast - Mapa Passagens");

        lblIconeTelaMapaPassagens.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ProgramBanner.png"))); // NOI18N

        javax.swing.GroupLayout PainelRelTituloPassageiroLayout = new javax.swing.GroupLayout(PainelRelTituloPassageiro);
        PainelRelTituloPassageiro.setLayout(PainelRelTituloPassageiroLayout);
        PainelRelTituloPassageiroLayout.setHorizontalGroup(
            PainelRelTituloPassageiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelRelTituloPassageiroLayout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(lblIconeTelaMapaPassagens, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(lblTituloMapaAssentos, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(276, Short.MAX_VALUE))
        );
        PainelRelTituloPassageiroLayout.setVerticalGroup(
            PainelRelTituloPassageiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelRelTituloPassageiroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelRelTituloPassageiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblIconeTelaMapaPassagens, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTituloMapaAssentos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        btnMostraMapaAssentos.setText("Acesse Mapa Acentos");
        btnMostraMapaAssentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostraMapaAssentosActionPerformed(evt);
            }
        });

        lblOpcaoMostra.setText("Escolher Assento:");

        javax.swing.GroupLayout painelSelecaoMapaAssentosLayout = new javax.swing.GroupLayout(painelSelecaoMapaAssentos);
        painelSelecaoMapaAssentos.setLayout(painelSelecaoMapaAssentosLayout);
        painelSelecaoMapaAssentosLayout.setHorizontalGroup(
            painelSelecaoMapaAssentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelSelecaoMapaAssentosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblOpcaoMostra, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMostraMapaAssentos, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1012, Short.MAX_VALUE))
        );
        painelSelecaoMapaAssentosLayout.setVerticalGroup(
            painelSelecaoMapaAssentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelSelecaoMapaAssentosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelSelecaoMapaAssentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOpcaoMostra, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMostraMapaAssentos))
                .addContainerGap(368, Short.MAX_VALUE))
        );

        tabMapaAssentos.addTab("Seleção Voo", painelSelecaoMapaAssentos);
        tabMapaAssentos.addTab("Assentos", jScrollPanelMapaAssentos);

        javax.swing.GroupLayout painelBotoesLayout = new javax.swing.GroupLayout(painelBotoes);
        painelBotoes.setLayout(painelBotoesLayout);
        painelBotoesLayout.setHorizontalGroup(
            painelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        painelBotoesLayout.setVerticalGroup(
            painelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 53, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabMapaAssentos)
            .addComponent(painelBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(PainelRelTituloPassageiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(218, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(83, Short.MAX_VALUE)
                .addComponent(tabMapaAssentos, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(PainelRelTituloPassageiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 511, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMostraMapaAssentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostraMapaAssentosActionPerformed
         new TelaMostraAssentos(true, 38, 22, 17, 3,3, 4); 
    }//GEN-LAST:event_btnMostraMapaAssentosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaEscolhaAssento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaEscolhaAssento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaEscolhaAssento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaEscolhaAssento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaEscolhaAssento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PainelRelTituloPassageiro;
    private javax.swing.JButton btnMostraMapaAssentos;
    private javax.swing.JScrollPane jScrollPanelMapaAssentos;
    private javax.swing.JLabel lblIconeTelaMapaPassagens;
    private javax.swing.JLabel lblOpcaoMostra;
    private javax.swing.JLabel lblTituloMapaAssentos;
    private javax.swing.JPanel painelBotoes;
    private javax.swing.JPanel painelSelecaoMapaAssentos;
    private javax.swing.JTabbedPane tabMapaAssentos;
    // End of variables declaration//GEN-END:variables
}
